### ISSUE TITLE
Docker screenshots mismatched between local and CI

### ISSUE THREAD

**Issue by j-lea** [fwouts/react-screenshot-test#298]
Hi! I've just started using react-screenshot-test and was so impressed by how easy it was to get running and how perfect it is for my use case, thanks! However I've hit a bit of an issue with screenshots mismatching between the ones I generate locally and those taken in circleCI. 

I am running both in Docker,  but the screenshots taken locally are missing a border around the component, whilst the ones in CI do have the border. Giving me the following diff for exactly the same code:
<img width="1402" alt="Screenshot 2021-05-07 at 15 36 56" src="https://user-images.githubusercontent.com/45389321/117469796-05876000-af4e-11eb-9b68-ed6f9c0e80a2.png">

**One thing to note**: the border is made using the `boxShadow` in the second div, rather than a normal border on the first div.

This is my component:
```
export const Button = () => {
  return (
    <div
      style={{
        boxSizing: 'border-box',
        borderRadius: '8px',
        padding: '20px',
        position: 'absolute',
        background: 'rgb(252, 248, 236)',
        boxShadow: 'rgba(0, 0, 0, 0.25) 0px 4px 4px 0px',
      }}
    >
      <div>
        <span
          style={{
            fontFamily: 'Roboto',
          }}
        >
          What needs to be done?
        </span>
      </div>
      <div
        style={{
          position: 'absolute',
          pointerEvents: 'none',
          inset: '0px',
          borderRadius: '8px',
          boxShadow: 'rgb(0, 0, 0) 0px 0px 0px 1px inset',
        }}
      ></div>
    </div>
  )
}
```

This is the test (copied from the example):
```
  ReactScreenshotTest.create('Button with border')
    .viewport('Desktop', {
      width: 1024,
      height: 768,
    })
    .viewport('iPhone X', {
      width: 375,
      height: 812,
      deviceScaleFactor: 3,
      isMobile: true,
      hasTouch: true,
      isLandscape: false,
    })
    .shoot('Default', <Button />)
    .run()
```

And this is my jest config in package.json:
```
  "jest": {
    "verbose": true,
    "testMatch": [
      "**/?(*.)+(spec|test).tsx"
    ],
    "transform": {
      "^.+\\.[t|j]sx?$": "babel-jest",
      "^.+\\.css$": "react-screenshot-test/css-transform"
    },
    "globalSetup": "react-screenshot-test/global-setup",
    "globalTeardown": "react-screenshot-test/global-teardown"
  },

```

And this is my circleCI.yaml
```
jobs:
  test:
    executor: default
    steps:
      - start_job
      - setup_remote_docker
      - restore_cache:
          keys:
            - node-cache-v2-{{ checksum "./package-lock.json" }}
      - run:
          name: Screenshot test
          command: ./ci-screenshot.sh // This contains npm install and npm run test
      - save_cache:
          key: node-cache-v2-{{ checksum "./package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - store_artifacts:
          path: ./screenshot_tests/diffs
      - finish_job
```
Let me know if you need any more info!
