### ISSUE TITLE
Fonts not injected

### ISSUE THREAD

**Issue by leicht-io** [fwouts/react-screenshot-test#81]
The generated HTML from ```React.createElement()``` doesn't convert the import paths from the fonts we're using in our library which results in the fonts not being applied.

The following is from the inline CSS from the generated HTML document:
```css
@font-face {
	font-family: 'Open Sans';
	font-style: normal;
	font-weight: 700;
	src: url("assets/fonts/OpenSans-Bold.woff2") format("woff2"), url("assets/fonts/OpenSans-Bold.woff") format("woff");
	unicode-range: U+000-5FF;
}
```
As you can see it tries to load the fonts from an absolute path which results in a 404.
Is there a way to solve this and can you point me in the right direction? :)

**Comment by leicht-io** [comment]
A possible solution could be to seek out all font imports and encode them to base64 and use them as follows:
```css
@font-face {
	font-family: 'Open Sans';
	font-style: normal;
	font-weight: 700;
        src: local('OpenSans-Bold'), url(data:application/font-woff2;charset=utf-8;base64,d09GRgABAAAAAIQYABMAAAAA/MAA) format('woff2');
	unicode-range: U+000-5FF;
}
```
